# Optional: Automated Secret Rotation Workflow
# This workflow can be triggered manually or scheduled
# Requires VERCEL_TOKEN secret to be set in GitHub repository settings

name: Rotate NEXTAUTH_SECRET

on:
  workflow_dispatch: # Manual trigger
    inputs:
      confirm:
        description: 'Type "rotate" to confirm secret rotation'
        required: true
        default: ''
  # Uncomment for monthly automatic rotation
  # schedule:
  #   - cron: '0 2 1 * *'  # First day of month at 2 AM UTC

jobs:
  rotate-secret:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'rotate' || github.event_name == 'schedule'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'

      - name: Install Vercel CLI
        run: npm i -g vercel

      - name: Generate new secret
        id: secret
        run: |
          NEW_SECRET=$(openssl rand -base64 32)
          echo "::add-mask::$NEW_SECRET"
          echo "secret=$NEW_SECRET" >> $GITHUB_OUTPUT

      - name: Update Vercel environment variable
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: |
          # Remove old secret
          vercel env rm NEXTAUTH_SECRET production --yes --token $VERCEL_TOKEN || true

          # Add new secret
          echo "${{ steps.secret.outputs.secret }}" | vercel env add NEXTAUTH_SECRET production --token $VERCEL_TOKEN

      - name: Trigger redeployment
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: |
          vercel --prod --token $VERCEL_TOKEN

      - name: Create issue for notification
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🔄 NEXTAUTH_SECRET Rotated Successfully',
              body: `
              ## Security Update Complete
              
              The NEXTAUTH_SECRET has been successfully rotated on ${new Date().toISOString()}.
              
              ### Impact:
              - ✅ New secret deployed to production
              - ⚠️ All user sessions invalidated
              - 🔄 Application redeployed
              
              ### Next Steps:
              - [ ] Monitor application for authentication issues
              - [ ] Verify user sign-in flow is working
              - [ ] Update local development environment if needed
              
              ### Security Notes:
              - The old secret is no longer valid
              - Users will need to sign in again
              - JWT tokens have been invalidated
              
              This issue was created automatically by the secret rotation workflow.
              `,
              labels: ['security', 'automated']
            })
